[34mBINOP_CALL[m
|  [0ma[m
|  [34mBINOP_COMMA[m
|  |  [33m1[m
|  |  [33m2[m
 -- tok: ;
[34mBINOP_CALL[m
|  [0ma[m
|  [34mBINOP_COMMA[m
|  |  [34mBINOP_COMMA[m
|  |  |  [33m1[m
|  |  |  [33m2[m
|  |  [33m3[m
 -- tok: ;
[34mBINOP_CALL[m
|  [0ma[m
|  [31m(nil)[m
 -- tok: ;
[34mBINOP_CALL[m
|  [0ma[m
|  [34mBINOP_CALL[m
|  |  [0mb[m
|  |  [34mBINOP_COMMA[m
|  |  |  [33m1[m
|  |  |  [33m2[m
 -- tok: ;
[34mBINOP_CALL[m
|  [0ma[m
|  [34mBINOP_COMMA[m
|  |  [33m0[m
|  |  [34mBINOP_CALL[m
|  |  |  [0mb[m
|  |  |  [34mBINOP_COMMA[m
|  |  |  |  [33m1[m
|  |  |  |  [33m2[m
 -- tok: ;
[34mBINOP_CALL[m
|  [0ma[m
|  [34mBINOP_COMMA[m
|  |  [34mBINOP_CALL[m
|  |  |  [0mb[m
|  |  |  [34mBINOP_COMMA[m
|  |  |  |  [33m1[m
|  |  |  |  [33m2[m
|  |  [34mBINOP_CALL[m
|  |  |  [0mc[m
|  |  |  [34mBINOP_COMMA[m
|  |  |  |  [33m3[m
|  |  |  |  [33m4[m
 -- tok: ;
[34mBINOP_CALL[m
|  [0ma[m
|  [34mBINOP_COMMA[m
|  |  [34mBINOP_CALL[m
|  |  |  [0mc[m
|  |  |  [34mBINOP_COMMA[m
|  |  |  |  [33m3[m
|  |  |  |  [33m4[m
|  |  [33m0[m
 -- tok: ;
[34mBINOP_COMMA[m
|  [34mBINOP_CALL[m
|  |  [0ma[m
|  |  [33m1[m
|  [34mUNOP_MINUS[m
|  |  [33m1[m
 -- tok: ;
[34mBINOP_CALL[m
|  [34mBINOP_CALL[m
|  |  [0ma[m
|  |  [31m(nil)[m
|  [31m(nil)[m
 -- tok: ;
[34mBINOP_CALL[m
|  [34mBINOP_CALL[m
|  |  [0ma[m
|  |  [31m(nil)[m
|  [31m(nil)[m
 -- tok: ;
[34mBINOP_CALL[m
|  [34mBINOP_CALL[m
|  |  [34mBINOP_CALL[m
|  |  |  [0ma[m
|  |  |  [33m1[m
|  |  [33m2[m
|  [33m3[m
 -- tok: ;
[34mBINOP_CALL[m
|  [0ma[m
|  [34mBINOP_COMMA[m
|  |  [34mBINOP_COMMA[m
|  |  |  [33m1[m
|  |  |  [33m2[m
|  |  [33m3[m
 -- tok: ;
