[34mCOMPLIT[m
|  [32mbidoof[m
|  .name
|  |  [36m":3"[m
|  .level
|  |  [33m42[m
[1m[test/in/expr-tree/complit:1][m (bidoof){.name= ":3", .level= 42,}; [1m##[m  -- tok: ;
[34mCOMPLIT[m
|  [32mint[m
|  (no desig)
|  |  [33m0[m
[1m[test/in/expr-tree/complit:2][m (int){0}; [1m##[m  -- tok: ;
[34mCOMPLIT[m
|  [32mabc[m
|  .a[(0)].b.c[(-(1))]
|  |  [34mBINOP_COMMA[m
|  |  |  [33m17[m
|  |  |  [33m5[m
[1m[test/in/expr-tree/complit:3][m (abc){.a[0].b.c[-1]= (17,5)}; [1m##[m  -- tok: ;
