[34mBINOP_TERNCOND[m
|  [33m1[m
|  [34mBINOP_TERNBRANCH[m
|  |  [33m2[m
|  |  [33m3[m
 -- tok: ;
[34mBINOP_TERNCOND[m
|  [33m1[m
|  [34mBINOP_TERNBRANCH[m
|  |  [33m2[m
|  |  [34mBINOP_TERNCOND[m
|  |  |  [33m3[m
|  |  |  [34mBINOP_TERNBRANCH[m
|  |  |  |  [33m4[m
|  |  |  |  [33m5[m
 -- tok: ;
[34mBINOP_TERNCOND[m
|  [0ma[m
|  [34mBINOP_TERNBRANCH[m
|  |  [34mBINOP_COMMA[m
|  |  |  [0mb[m
|  |  |  [0mc[m
|  |  [34mBINOP_COMMA[m
|  |  |  [0md[m
|  |  |  [0me[m
 -- tok: ;
[34mBINOP_TERNCOND[m
|  [0ma[m
|  [34mBINOP_TERNBRANCH[m
|  |  [34mBINOP_COMMA[m
|  |  |  [0mb[m
|  |  |  [0mc[m
|  |  [0md[m
 -- tok: ;
[34mBINOP_TERNCOND[m
|  [0ma[m
|  [34mBINOP_TERNBRANCH[m
|  |  [34mBINOP_COMMA[m
|  |  |  [0mb[m
|  |  |  [0mc[m
|  |  [34mBINOP_COMMA[m
|  |  |  [0md[m
|  |  |  [0me[m
 -- tok: ;
[34mBINOP_TERNCOND[m
|  [33m1[m
|  [34mBINOP_TERNBRANCH[m
|  |  [36m"one"[m
|  |  [34mBINOP_TERNCOND[m
|  |  |  [33m2[m
|  |  |  [34mBINOP_TERNBRANCH[m
|  |  |  |  [36m"two"[m
|  |  |  |  [34mBINOP_TERNCOND[m
|  |  |  |  |  [33m3[m
|  |  |  |  |  [34mBINOP_TERNBRANCH[m
|  |  |  |  |  |  [36m"tree"[m
|  |  |  |  |  |  [36m"sun"[m
 -- tok: ;
