[34mBINOP_ADD[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
[34mBINOP_ADD[m
|  [33m1[m
|  [34mBINOP_MUL[m
|  |  [33m2[m
|  |  [33m3[m
 -- tok: ;
[34mBINOP_MUL[m
|  [34mBINOP_ADD[m
|  |  [33m1[m
|  |  [33m2[m
|  [33m3[m
 -- tok: ;
[33m0[m
 -- tok: ;
[34mBINOP_CALL[m
|  [0mstrlen[m
|  [36m"coucou"[m
 -- tok: ;
[34mBINOP_CALL[m
|  [34mUNOP_PMEMBER[m
|  |  [0ma[m
|  |  ->b
|  [34mUNOP_PLUS[m
|  |  [33m0[m
 -- tok: ;
[34mBINOP_ADD[m
|  [34mBINOP_ADD[m
|  |  [34mBINOP_ADD[m
|  |  |  [0ma[m
|  |  |  [0mb[m
|  |  [0mc[m
|  [0md[m
 -- tok: ;
[34mBINOP_ADD[m
|  [0ma[m
|  [34mBINOP_DIV[m
|  |  [34mBINOP_MUL[m
|  |  |  [0mb[m
|  |  |  [0mc[m
|  |  [0md[m
 -- tok: ;
[34mBINOP_ASGN[m
|  [0ma[m
|  [34mBINOP_ASGN[m
|  |  [0mb[m
|  |  [0mc[m
 -- tok: ;
[34mBINOP_LOR[m
|  [34mBINOP_EQ[m
|  |  [33m'_'[m
|  |  [0mc[m
|  [34mBINOP_LAND[m
|  |  [34mBINOP_LE[m
|  |  |  [33m'a'[m
|  |  |  [34mBINOP_BOR[m
|  |  |  |  [0mc[m
|  |  |  |  [33m32[m
|  |  [34mBINOP_GE[m
|  |  |  [33m'z'[m
|  |  |  [34mBINOP_BOR[m
|  |  |  |  [0mc[m
|  |  |  |  [33m32[m
 -- tok: ;
[34mBINOP_ASGN_BSHL[m
|  [0mn[m
|  [34mBINOP_LT[m
|  |  [34mBINOP_BSHR[m
|  |  |  [0mn[m
|  |  |  [33m1[m
|  |  [33m2[m
 -- tok: ;
[34mBINOP_ASGN_BSHR[m
|  [0mn[m
|  [34mBINOP_GT[m
|  |  [34mBINOP_BSHL[m
|  |  |  [0mn[m
|  |  |  [33m1[m
|  |  [33m2[m
 -- tok: ;
[34mBINOP_ASGN[m
|  [0mESC[m
|  [34mBINOP_BXOR[m
|  |  [33m'['[m
|  |  [33m64[m
 -- tok: ;
[34mBINOP_TERNCOND[m
|  [34mUNOP_LNOT[m
|  |  [34mBINOP_BAND[m
|  |  |  [34mBINOP_NE[m
|  |  |  |  [33m0[m
|  |  |  |  [34mUNOP_PRE_DEC[m
|  |  |  |  |  [0mz[m
|  |  |  [33m1[m
|  [34mBINOP_TERNBRANCH[m
|  |  [36m"no"[m
|  |  [36m"yes"[m
 -- tok: ;
[34mBINOP_ASGN_ADD[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
[34mBINOP_ASGN_SUB[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
[34mBINOP_ASGN_MUL[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
[34mBINOP_ASGN_DIV[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
[34mBINOP_ASGN_REM[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
[34mBINOP_ASGN_BAND[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
[34mBINOP_ASGN_BOR[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
[34mBINOP_ASGN_BXOR[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
