[34mBINOP_ADD[m
|  [0ma[m
|  [0mb[m
 -- tok: ;
[34mBINOP_ADD[m
|  [33m1[m
|  [34mBINOP_MUL[m
|  |  [33m2[m
|  |  [33m3[m
 -- tok: ;
[34mBINOP_MUL[m
|  [34mBINOP_ADD[m
|  |  [33m1[m
|  |  [33m2[m
|  [33m3[m
 -- tok: ;
[33m0[m
 -- tok: ;
[34mBINOP_CALL[m
|  [0mstrlen[m
|  [36m"coucou"[m
 -- tok: ;
[34mBINOP_CALL[m
|  [34mUNOP_PMEMBER[m
|  |  [0ma[m
|  |  ->b
|  [33m0[m
 -- tok: ;
[34mBINOP_ADD[m
|  [34mBINOP_ADD[m
|  |  [34mBINOP_ADD[m
|  |  |  [0ma[m
|  |  |  [0mb[m
|  |  [0mc[m
|  [0md[m
 -- tok: ;
[34mBINOP_ADD[m
|  [0ma[m
|  [34mBINOP_DIV[m
|  |  [34mBINOP_MUL[m
|  |  |  [0mb[m
|  |  |  [0mc[m
|  |  [0md[m
 -- tok: ;
[34mBINOP_ASGN[m
|  [0ma[m
|  [34mBINOP_ASGN[m
|  |  [0mb[m
|  |  [0mc[m
 -- tok: ;
