1
[1m[test/in/comp-code/cfolded:1][m 1; [1m##[m  -- tok: ;
17
[1m[test/in/comp-code/cfolded:2][m 17; [1m##[m  -- tok: ;
3
[1m[test/in/comp-code/cfolded:3][m 1+2; [1m##[m  -- tok: ;
'a'
[1m[test/in/comp-code/cfolded:4][m 'a'; [1m##[m  -- tok: ;
1.200000
[1m[test/in/comp-code/cfolded:5][m 1.2; [1m##[m  -- tok: ;
7
[1m[test/in/comp-code/cfolded:6][m 1+2*3; [1m##[m  -- tok: ;
0
[1m[test/in/comp-code/cfolded:7][m (1-2)/3; [1m##[m  -- tok: ;
-0.333333
[1m[test/in/comp-code/cfolded:8][m (1-2)/3.; [1m##[m  -- tok: ;
42
[1m[test/in/comp-code/cfolded:9][m 0x2a; [1m##[m  -- tok: ;
31
[1m[test/in/comp-code/cfolded:10][m 0x1f; [1m##[m  -- tok: ;
62.000000
[1m[test/in/comp-code/cfolded:11][m 0x1fp1; [1m##[m  -- tok: ;
9.000000
[1m[test/in/comp-code/cfolded:12][m 0x1.2p3; [1m##[m  -- tok: ;
416
[1m[test/in/comp-code/cfolded:13][m 0o640; [1m##[m  -- tok: ;
42
[1m[test/in/comp-code/cfolded:14][m 0b101010; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:15][m -1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:16][m -1l; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:17][m -1ll; [1m##[m  -- tok: ;
1
[1m[test/in/comp-code/cfolded:18][m 1ul; [1m##[m  -- tok: ;
1
[1m[test/in/comp-code/cfolded:19][m 1lu; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:20][m -1u; [1m##[m  -- tok: ;
2.000000
[1m[test/in/comp-code/cfolded:21][m 2f; [1m##[m  -- tok: ;
340000.000000
[1m[test/in/comp-code/cfolded:22][m 3.4e5f; [1m##[m  -- tok: ;
0.500000
[1m[test/in/comp-code/cfolded:23][m .5; [1m##[m  -- tok: ;
5.000000
[1m[test/in/comp-code/cfolded:24][m 5.; [1m##[m  -- tok: ;
3
[1m[test/in/comp-code/cfolded:25][m 3ull; [1m##[m  -- tok: ;
3
[1m[test/in/comp-code/cfolded:26][m 3llu; [1m##[m  -- tok: ;
1024
[1m[test/in/comp-code/cfolded:27][m 1'024; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:29][m (char)'\xff'; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:30][m (char)(unsigned char)-1; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:31][m (char)(signed char)-1; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:32][m (char)(short)-1; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:33][m (char)(unsigned short)-1; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:34][m (char)-1; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:35][m (char)-1u; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:36][m (char)-1l; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:37][m (char)-1ul; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:38][m (char)-1.0f; [1m##[m  -- tok: ;
'\xff'
[1m[test/in/comp-code/cfolded:39][m (char)-1.0; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:40][m (unsigned char)'\xff'; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:41][m (unsigned char)(unsigned char)-1; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:42][m (unsigned char)(signed char)-1; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:43][m (unsigned char)(short)-1; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:44][m (unsigned char)(unsigned short)-1; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:45][m (unsigned char)-1; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:46][m (unsigned char)-1u; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:47][m (unsigned char)-1l; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:48][m (unsigned char)-1ul; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:49][m (unsigned char)-1.0f; [1m##[m  -- tok: ;
0xff
[1m[test/in/comp-code/cfolded:50][m (unsigned char)-1.0; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:51][m (signed char)'\xff'; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:52][m (signed char)(unsigned char)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:53][m (signed char)(signed char)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:54][m (signed char)(short)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:55][m (signed char)(unsigned short)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:56][m (signed char)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:57][m (signed char)-1u; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:58][m (signed char)-1l; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:59][m (signed char)-1ul; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:60][m (signed char)-1.0f; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:61][m (signed char)-1.0; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:62][m (short)'\xff'; [1m##[m  -- tok: ;
255
[1m[test/in/comp-code/cfolded:63][m (short)(unsigned char)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:64][m (short)(signed char)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:65][m (short)(short)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:66][m (short)(unsigned short)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:67][m (short)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:68][m (short)-1u; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:69][m (short)-1l; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:70][m (short)-1ul; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:71][m (short)-1.0f; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:72][m (short)-1.0; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:73][m (unsigned short)'\xff'; [1m##[m  -- tok: ;
255
[1m[test/in/comp-code/cfolded:74][m (unsigned short)(unsigned char)-1; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:75][m (unsigned short)(signed char)-1; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:76][m (unsigned short)(short)-1; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:77][m (unsigned short)(unsigned short)-1; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:78][m (unsigned short)-1; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:79][m (unsigned short)-1u; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:80][m (unsigned short)-1l; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:81][m (unsigned short)-1ul; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:82][m (unsigned short)-1.0f; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:83][m (unsigned short)-1.0; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:84][m (int)'\xff'; [1m##[m  -- tok: ;
255
[1m[test/in/comp-code/cfolded:85][m (int)(unsigned char)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:86][m (int)(signed char)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:87][m (int)(short)-1; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:88][m (int)(unsigned short)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:89][m (int)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:90][m (int)-1u; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:91][m (int)-1l; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:92][m (int)-1ul; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:93][m (int)-1.0f; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:94][m (int)-1.0; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:95][m (unsigned int)'\xff'; [1m##[m  -- tok: ;
255
[1m[test/in/comp-code/cfolded:96][m (unsigned int)(unsigned char)-1; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:97][m (unsigned int)(signed char)-1; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:98][m (unsigned int)(short)-1; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:99][m (unsigned int)(unsigned short)-1; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:100][m (unsigned int)-1; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:101][m (unsigned int)-1u; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:102][m (unsigned int)-1l; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:103][m (unsigned int)-1ul; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:104][m (unsigned int)-1.0f; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:105][m (unsigned int)-1.0; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:106][m (long)'\xff'; [1m##[m  -- tok: ;
255
[1m[test/in/comp-code/cfolded:107][m (long)(unsigned char)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:108][m (long)(signed char)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:109][m (long)(short)-1; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:110][m (long)(unsigned short)-1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:111][m (long)-1; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:112][m (long)-1u; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:113][m (long)-1l; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:114][m (long)-1ul; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:115][m (long)-1.0f; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:116][m (long)-1.0; [1m##[m  -- tok: ;
18446744073709551615
[1m[test/in/comp-code/cfolded:117][m (unsigned long)'\xff'; [1m##[m  -- tok: ;
255
[1m[test/in/comp-code/cfolded:118][m (unsigned long)(unsigned char)-1; [1m##[m  -- tok: ;
18446744073709551615
[1m[test/in/comp-code/cfolded:119][m (unsigned long)(signed char)-1; [1m##[m  -- tok: ;
18446744073709551615
[1m[test/in/comp-code/cfolded:120][m (unsigned long)(short)-1; [1m##[m  -- tok: ;
65535
[1m[test/in/comp-code/cfolded:121][m (unsigned long)(unsigned short)-1; [1m##[m  -- tok: ;
18446744073709551615
[1m[test/in/comp-code/cfolded:122][m (unsigned long)-1; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:123][m (unsigned long)-1u; [1m##[m  -- tok: ;
18446744073709551615
[1m[test/in/comp-code/cfolded:124][m (unsigned long)-1l; [1m##[m  -- tok: ;
18446744073709551615
[1m[test/in/comp-code/cfolded:125][m (unsigned long)-1ul; [1m##[m  -- tok: ;
18446744073709551615
[1m[test/in/comp-code/cfolded:126][m (unsigned long)-1.0f; [1m##[m  -- tok: ;
18446744073709551615
[1m[test/in/comp-code/cfolded:127][m (unsigned long)-1.0; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:128][m (float)'\xff'; [1m##[m  -- tok: ;
255.000000
[1m[test/in/comp-code/cfolded:129][m (float)(unsigned char)-1; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:130][m (float)(signed char)-1; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:131][m (float)(short)-1; [1m##[m  -- tok: ;
65535.000000
[1m[test/in/comp-code/cfolded:132][m (float)(unsigned short)-1; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:133][m (float)-1; [1m##[m  -- tok: ;
4294967296.000000
[1m[test/in/comp-code/cfolded:134][m (float)-1u; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:135][m (float)-1l; [1m##[m  -- tok: ;
18446744073709551616.000000
[1m[test/in/comp-code/cfolded:136][m (float)-1ul; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:137][m (float)-1.0f; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:138][m (float)-1.0; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:139][m (double)'\xff'; [1m##[m  -- tok: ;
255.000000
[1m[test/in/comp-code/cfolded:140][m (double)(unsigned char)-1; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:141][m (double)(signed char)-1; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:142][m (double)(short)-1; [1m##[m  -- tok: ;
65535.000000
[1m[test/in/comp-code/cfolded:143][m (double)(unsigned short)-1; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:144][m (double)-1; [1m##[m  -- tok: ;
4294967295.000000
[1m[test/in/comp-code/cfolded:145][m (double)-1u; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:146][m (double)-1l; [1m##[m  -- tok: ;
18446744073709551616.000000
[1m[test/in/comp-code/cfolded:147][m (double)-1ul; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:148][m (double)-1.0f; [1m##[m  -- tok: ;
-1.000000
[1m[test/in/comp-code/cfolded:149][m (double)-1.0; [1m##[m  -- tok: ;
