1
[1m[test/in/comp-code/cfolded:1][m 1; [1m##[m  -- tok: ;
17
[1m[test/in/comp-code/cfolded:2][m 17; [1m##[m  -- tok: ;
3
[1m[test/in/comp-code/cfolded:3][m 1+2; [1m##[m  -- tok: ;
'a'
[1m[test/in/comp-code/cfolded:4][m 'a'; [1m##[m  -- tok: ;
1.200000
[1m[test/in/comp-code/cfolded:5][m 1.2; [1m##[m  -- tok: ;
7
[1m[test/in/comp-code/cfolded:6][m 1+2*3; [1m##[m  -- tok: ;
0
[1m[test/in/comp-code/cfolded:7][m (1-2)/3; [1m##[m  -- tok: ;
-0.333333
[1m[test/in/comp-code/cfolded:8][m (1-2)/3.; [1m##[m  -- tok: ;
42
[1m[test/in/comp-code/cfolded:9][m 0x2a; [1m##[m  -- tok: ;
31
[1m[test/in/comp-code/cfolded:10][m 0x1f; [1m##[m  -- tok: ;
62.000000
[1m[test/in/comp-code/cfolded:11][m 0x1fp1; [1m##[m  -- tok: ;
9.000000
[1m[test/in/comp-code/cfolded:12][m 0x1.2p3; [1m##[m  -- tok: ;
416
[1m[test/in/comp-code/cfolded:13][m 0o640; [1m##[m  -- tok: ;
42
[1m[test/in/comp-code/cfolded:14][m 0b101010; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:15][m -1; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:16][m -1l; [1m##[m  -- tok: ;
-1
[1m[test/in/comp-code/cfolded:17][m -1ll; [1m##[m  -- tok: ;
1
[1m[test/in/comp-code/cfolded:18][m 1ul; [1m##[m  -- tok: ;
1
[1m[test/in/comp-code/cfolded:19][m 1lu; [1m##[m  -- tok: ;
4294967295
[1m[test/in/comp-code/cfolded:20][m -1u; [1m##[m  -- tok: ;
2.000000
[1m[test/in/comp-code/cfolded:21][m 2f; [1m##[m  -- tok: ;
340000.000000
[1m[test/in/comp-code/cfolded:22][m 3.4e5f; [1m##[m  -- tok: ;
0.500000
[1m[test/in/comp-code/cfolded:23][m .5; [1m##[m  -- tok: ;
5.000000
[1m[test/in/comp-code/cfolded:24][m 5.; [1m##[m  -- tok: ;
3
[1m[test/in/comp-code/cfolded:25][m 3ull; [1m##[m  -- tok: ;
3
[1m[test/in/comp-code/cfolded:26][m 3llu; [1m##[m  -- tok: ;
1024
[1m[test/in/comp-code/cfolded:27][m 1'024; [1m##[m  -- tok: ;
