a: int con -- tok: ;
ld: double com lon -- tok: ;
ar: [0]int -- tok: ,
sfdsbbfsbdfb: int -- tok: ;
ppp: *(*(char)) -- tok: ;
y: char -- tok: ;
yy: *(char) con -- tok: ;
yyy: *((void) -> char) -- tok: ;
yyyy: *([0]char) -- tok: ;
v: int sig -- tok: ;
typ b: float -- tok: ;
c: int lon lon -- tok: ,
d: *(int lon lon) con -- tok: ,
e: int lon lon -- tok: ;
f: () -> void -- tok: ;
g: (void) -> void -- tok: ;
sta aa: () -> *(int) -- tok: ,
sta bb: int -- tok: ;
laksdjf: (c: char, i: int, f: float, d: double) -> int uns -- tok: ;
x: str S -- tok: ;
z: int sig -- tok: ;
fst: enu E1{ /*TODO*/ } -- tok: ,
lsdkfjsldf: enu E1{ /*TODO*/ } -- tok: ;
sec: enu { /*TODO*/ } -- tok: ;
trd: enu E3{ /*TODO*/ } -- tok: ;
b: some_t -- tok: ;
v: enu E{ /*TODO*/ } -- tok: ;
w: str S {
        a: 
        b: 
        c: 
    } -- tok: ;
b: int -- tok: ;
fff: str {
    } -- tok: ;
a: int -- tok: ;
sta b: () -> *(int con vol inl uns lon lon) con res vol -- tok: ;
f: int -- tok: ;
g: void -- tok: {
h: (void) -> int -- tok: ;
