a: [34mconst[m [32mint[m -- tok: ;
ld: [34mcomplex[m [34mlong[m [32mdouble[m -- tok: ;
ar: [34marr[m[32, [32mint[m] -- tok: ,
sfdsbbfsbdfb: [32mint[m -- tok: ;
ppp: [34mptr[m[[34mptr[m[[32mchar[m]] -- tok: ;
y: [32mchar[m -- tok: ;
yy: [34mconst[m [34mptr[m[[32mchar[m] -- tok: ;
yyy: [34mptr[m[[34mfun[m([36mvoid[m) -> [32mchar[m] -- tok: ;
yyyy: [34mptr[m[[34marr[m[2, [32mchar[m]] -- tok: ;
v: [34msigned[m [32mint[m -- tok: ;
[36mtypedef[m b: [32mfloat[m -- tok: ;
c: [34mlong[m [34mlong[m [32mint[m -- tok: ,
d: [34mconst[m [34mptr[m[[34mlong[m [34mlong[m [32mint[m] -- tok: ,
e: [34mlong[m [34mlong[m [32mint[m -- tok: ;
f: [34mfun[m() -> [32mvoid[m -- tok: ;
g: [34mfun[m([36mvoid[m) -> [32mvoid[m -- tok: ;
[36mstatic[m aa: [34mfun[m() -> [34mptr[m[[32mint[m] -- tok: ,
[36mstatic[m bb: [32mint[m -- tok: ;
laksdjf: [34mfun[m(c: [32mchar[m, i: [32mint[m, f: [32mfloat[m, d: [32mdouble[m) -> [34munsigned[m [32mint[m -- tok: ;
x: [34mstruct[m S -- tok: ;
z: [34msigned[m [32mint[m -- tok: ;
fst: [34menum[m E1 {ONE, TWO} -- tok: ,
lsdkfjsldf: [34menum[m E1 {ONE, TWO} -- tok: ;
sec: [34menum[m {ONN, TWW} -- tok: ;
trd: [34menum[m E3 {} -- tok: ;
[36mstatic[m crap: [34mfun[m(: [32mint[m, : [34mlong[m [32mint[m, : [34mshort[m [32mint[m) -> [32mint[m -- tok: ;
ddd: [34mptr[m[[34mptr[m[[34mfun[m() -> [32mvoid[m]] -- tok: ;
b: [32msome_t[m -- tok: ;
v: [34menum[m E {A, B, C} -- tok: ;
w: [34mstruct[m S {a: [32mint[m, b: [32mint[m, c: [32mint[m} -- tok: ;
b: [32mint[m -- tok: ;
fff: [34mstruct[m {} -- tok: ;
outer: [34mstruct[m {middle: [34mstruct[m {inner: [32mint[m}} -- tok: ;
a: [32mint[m -- tok: ;
[36mstatic[m b: [34mfun[m() -> [34mconst[m [34mrestrict[m [34mvolatile[m [34mptr[m[[34mconst[m [34mvolatile[m [34minline[m [34munsigned[m [34mlong[m [34mlong[m [32mint[m] -- tok: ;
c: [32mint[m -- tok: ,
d: [34mfun[m([36mvoid[m) -> [32mint[m -- tok: ,
e: [34marr[m[3, [34marr[m[2, [34marr[m[1, [32mint[m]]] -- tok: ;
f: [32mint[m -- tok: ;
g: [34mfun[m() -> [32mvoid[m -- tok: {
h: [34mfun[m(: [32mint[m) -> [34mptr[m[[34mfun[m([36mvoid[m) -> [32mint[m] -- tok: ;
[36mtypedef[m B: [34munion[m {} -- tok: ,
[36mtypedef[m pB: [34mptr[m[[34munion[m {}] -- tok: ;
begin: [32mint[m -- tok: ;
[36mstatic[m aa: [34mstruct[m {a: [32mint[m, b: [32mint[m, c: [34mptr[m[[34mconst[m [32mchar[m]} -- tok: ;
a: [34munion[m aaaaa -- tok: ;
: [34mstruct[m S {} -- tok: ;
: [34menum[m E {A, B, C} -- tok: ;
end: [32mint[m -- tok: ;
a: [34munsigned[m [32mchar[m -- tok: ;
