[36mextern[m a: [34mfun[m([36mvoid[m) -> [32mint[m
[1m[-:3][m int a(void); [1m##[m  -- tok: ;
[36mstatic[m a_adapt_call: [34mfun[m(ret: [34mptr[m[[32mchar[m], args: [34mptr[m[[34mptr[m[[32mchar[m]]) -> [32mvoid[m
[1m[-:4][m void a_adapt_call(char* ret, char** args) { [1m##[m  -- tok: {
[36mstatic[m a_adapt_type: [34mconst[m [34mstruct[m adpt_type
[1m[-:8][m static struct adpt_type const a_adapt_type = { [1m##[m  -- tok: =
[36mstatic[m adptns_int_a: [34marr[m[*, [34mconst[m [34mstruct[m adpt_item]
[1m[-:19][m static struct adpt_item const adptns_int_a[] = { [1m##[m  -- tok: =
