[test/in/tok-stream/ifs:  5]	one
[test/in/tok-stream/ifs:  5]	&
[test/in/tok-stream/ifs:  5]	two
[test/in/tok-stream/ifs: 28]	(
[test/in/tok-stream/ifs: 28]	1
[test/in/tok-stream/ifs: 28]	+
[test/in/tok-stream/ifs: 28]	2
[test/in/tok-stream/ifs: 28]	)
[test/in/tok-stream/ifs: 28]	!
[test/in/tok-stream/ifs: 37]	coucou
[test/in/tok-stream/ifs: 40]	coucou
[test/in/tok-stream/ifs: 43]	coucou
[test/in/tok-stream/ifs: 46]	coucou
[test/in/tok-stream/ifs: 43]	coucou
[yeye: 18]	coucou
[test/in/tok-stream/include/coucou.h:  1]	coucou
[1m[yeye:23][m  [1m##[m Error: "Success"
Stopping at preprocessor error
