[test/in/tok-stream/vamacro:  8]	struct
[test/in/tok-stream/vamacro:  8]	idk
[test/in/tok-stream/vamacro:  8]	a
[test/in/tok-stream/vamacro:  8]	=
[test/in/tok-stream/vamacro:  8]	{
[test/in/tok-stream/vamacro:  8]	.
[test/in/tok-stream/vamacro:  8]	id
[test/in/tok-stream/vamacro:  8]	=
[test/in/tok-stream/vamacro:  8]	"hello "
[test/in/tok-stream/vamacro:  8]	"a"
[test/in/tok-stream/vamacro:  8]	,
[test/in/tok-stream/vamacro:  8]	.
[test/in/tok-stream/vamacro:  8]	init_str
[test/in/tok-stream/vamacro:  8]	=
[test/in/tok-stream/vamacro:  8]	"(.one= 1, .two= \"two\")"
[test/in/tok-stream/vamacro:  8]	,
[test/in/tok-stream/vamacro:  8]	}
[test/in/tok-stream/vamacro:  8]	;
[test/in/tok-stream/vamacro:  9]	struct
[test/in/tok-stream/vamacro:  9]	idk
[test/in/tok-stream/vamacro: 14]	salkdfjaslkjdflasjdf
[test/in/tok-stream/vamacro: 14]	=
[test/in/tok-stream/vamacro: 14]	{
[test/in/tok-stream/vamacro: 14]	.
[test/in/tok-stream/vamacro: 14]	id
[test/in/tok-stream/vamacro: 14]	=
[test/in/tok-stream/vamacro: 14]	"hello "
[test/in/tok-stream/vamacro: 14]	"salkdfjaslkjdflasjdf"
[test/in/tok-stream/vamacro: 14]	,
[test/in/tok-stream/vamacro: 14]	.
[test/in/tok-stream/vamacro: 14]	init_str
[test/in/tok-stream/vamacro: 14]	=
[test/in/tok-stream/vamacro: 14]	"(     .this= 0,     .is= 1,     .a= 2,     .test= 3, )"
[test/in/tok-stream/vamacro: 14]	,
[test/in/tok-stream/vamacro: 14]	}
[test/in/tok-stream/vamacro: 14]	;
[test/in/tok-stream/vamacro: 14]	
