/*-*/;
[1m[test/in/stmt-graph/other:2][m {} [1m##[m  -- tok: {
{
}
[1m[test/in/stmt-graph/other:3][m 0; [1m##[m  -- tok: 0
(0);
[1m[test/in/stmt-graph/other:4][m {;} [1m##[m  -- tok: {
{
    /*-*/;
}
[1m[test/in/stmt-graph/other:5][m char a; [1m##[m  -- tok: char
a: [32mchar[m;
[1m[test/in/stmt-graph/other:6][m int b = 0; [1m##[m  -- tok: int
b: [32mint[m = (0);
[1m[test/in/stmt-graph/other:7][m //float x, y; // TODO [1m##[m  -- tok: 
