[34mswitch[m (a)
    {
[36mcase[m 1:
        [34mbreak[m;
[36mcase[m 4:
        [34mbreak[m;
[36mcase[m 3:
        [34mbreak[m;
[36mcase[m 2:
        [34mbreak[m;
[36mdefault[m:
        [34mcontinue[m;
    }
[1m[test/in/stmt-graph/switch:9][m switch (0); [1m##[m  -- tok: switch
[34mswitch[m (0)
    /*-*/;
[1m[test/in/stmt-graph/switch:9][m switch (0); [1m##[m  -- tok: 
